Modify README.md
retronx-team/sys-clk-db pull request #6
Opened 2019-06-15 00:05 UTC by Mario-119

Updated README.md with the latest profiles from the RetroNX Discord as of writing this, and fixed the profiles for Let's Go Pikachu and Let's Go Eevee as per user reports of slowdown in Viridian Forest. 

I've also updated my ARMS and Mario Kart 8 Deluxe profiles with lower GPU clocks in order to further save battery life in handheld mode (they still run at a locked 60FPS even with the changes).

2019-06-15 14:35 UTC, m4xw commented
Please fix your line endings.

2019-06-17 08:34 UTC, p-sam requested changes

2019-06-17 08:34 UTC, p-sam commented on README.md
> +;VA-11 HALL-A
add a space between ; and text, do the same on the next line

2019-06-17 08:34 UTC, p-sam commented on README.md
> +;Resident Evil 4
same

2019-06-17 22:23 UTC, merged